name: wasmedge-macro-release

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

on:
  # workflow_dispatch:
  #   branches:
  #     - main
  push:
    branches:
      - feat/migrate-rust-sdk
    paths:
      - ".github/workflows/release-wasmedge-macro.yml"

jobs:
  release_wasmedge_macro:
    name: Create Release
    runs-on: ubuntu-22.04
    container:
      image: wasmedge/wasmedge:ubuntu-build-clang

    steps:
      - name: Checkout WasmEdge Rust SDK
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Checkout WasmEdge Runtime
        uses: actions/checkout@v3
        with:
          repository: WasmEdge/WasmEdge
          path: WasmEdge

      - name: Build WasmEdge with Release mode
        working-directory: WasmEdge
        run: |
          apt update
          apt install -y software-properties-common libboost-all-dev llvm-15-dev liblld-15-dev ninja-build
          cmake -Bbuild -GNinja -DCMAKE_BUILD_TYPE=Release -DWASMEDGE_PLUGIN_PROCESS=On .
          cmake --build build
          cmake --install build
          ldconfig

      - name: Install Rust v1.68
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.68

      - name: Dry run cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRIES_MACRO_TOKEN }}
        shell: bash
        run: |
          cargo publish --dry-run -p wasmedge-macro

      # - name: Publish
      #   if: github.ref == 'refs/heads/main'
      #   env:
      #     CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRIES_MACRO_TOKEN }}
      #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   shell: bash
      #   run: |
      #     cargo publish -p wasmedge-macro

      - name: Build API document
        run: |
          cargo doc -p wasmedge-macro --no-deps --target-dir=./target

      - name: Deploy API document
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: target/doc
          force_orphan: true
